### ISSUE TITLE
Make iocs using ads-deploy and check them into git

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/sample-delivery-system#26]
I haven't tested it, but I believe you could still use ads-ioc here - unless SDS has some additional module requirements, of course.

What you'd do is:
1. Use ads-deploy to create a single iocBoot directory
2. Rename the generated iocBoot directory + modify the generated `Makefile` (set the DB parameters as needed)
3. Copy/paste that boot directory and repeat the renaming + PV prefix setting process as needed

_Originally posted by @klauer in https://github.com/pcdshub/sample-delivery-system/pull/24#discussion_r877269603_

**Comment by wwright-slac** [comment]
Resolved in https://github.com/pcdshub/sample-delivery-system/pull/27
